Repository nest/nest-gpu, pull requests merged in 2022-05, with the labels that each got.

#29 Add NEST GPU logo
  doc/_static/img/nest_logo.png
  doc/conf.py
  doc/logo/nestgpu-logo.pdf
  doc/logo/nestgpu-logo.png
  doc/logo/nestgpu-logo.svg
Labels: S: High, T: Enhancement

#30 Remove unused and almost empty tutorials file from documentation
  doc/tutorials/index.rst
Labels: S: Normal, T: Maintenance

#13 Improve packing of spikes in GPU using MPI
  src/spike_mpi.cu
Labels: S: Normal, T: Enhancement

#32 Update spike recording for Potjans_2014 examples
  python/Potjans_2014/network.py
  python/Potjans_2014_hc/network.py
  python/Potjans_2014_s/network.py
Labels: S: High, T: Bug
